[project]
src = "src"

[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"

[networks.sepolia]
url = "${SEPOLIA_RPC_URL}"
save_to_db = false
default_account_name = "sep1"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"



[networks.sepolia.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"


# You can view all configuration options at https://cyfrin.github.io/moccasin/all_moccasin_toml_parameters.html
